version: '3.9'

services:
  app:
    build:
      context: .
    ports:
      - "3000:3000"
      - "5000:5000"
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: